Make the toolbox helper have a compilation opt-out
The idea is that when doing QA, it would be nice to use the production
build to get a sense for the release-build speed and get faster
feedback.

diff --git a/bin/toolbox b/bin/toolbox
--- a/bin/toolbox
+++ b/bin/toolbox
@@ -2,5 +2,16 @@
 
 set -e
 
+# development
+toolbox="cargo run --package toolbox --"
+
+if ! test -z "$FAST"; then
+  toolbox="target/release/toolbox"
+  if ! test -f "$toolbox"; then
+    echo "[$(date)] Building missing fast build of toolbox"
+    time cargo build --quiet --release --package toolbox
+  fi
+fi
+
 RUST_LOG="psst=debug" \
-  cargo run --package toolbox -- $*
+  $toolbox $*
